### PR TITLE
Roller Stop

### PR DESCRIPTION
**Pull request by mastermind-mayhem**

### CODE REVIEW

**Comment by mathyourlife** [comment]
Why is this PR from the `Test` branch and not the `workingCode` branch that we were using last night?

**Comment by mastermind-mayhem** [comment]
Because the working code branch had everything al ready in the testing phase for the arm

**Comment by mathyourlife** [comment]
Right, the goal would be to merge that entire branch into main. then start a new branch for testing instead of keeping a branch that will drift further and further away from what's in main accumulating merge conflicts.

This is the rough idea of what I was thinking.

1) Make sure your local code is up to date.

```
git checkout workingCode
git pull
```

2) Change txt files back to java files.
3) `./gradlew build` to test build.
4) Patch build errors.
5) Repeat 3 and 4 as needed until a clean build.
6) Create PR for `workingCode` into `main`.
7) Resolve any merge conflicts.
8) Merge the PR (don't delete the `workingCode` branch in case we want to go back to it at some point tonight)
9) This merged code in `main` can be what everyone starts with today.
10) Team members that are working on finessing subsystems that were vetted last night can create branches like `tweaking-drivetrain-responsiveness` or `switching-roller-trigger-location'.
11) Team members working on vetting the next subsystem can create a branch `integration-testing-hanger-system`.  If needed in this branch they can re-comment out subsystems they don't want to activate.

**Review by mathyourlife — APPROVED** [review]
formatting changes look fine.  the rest of the changes made it in with `workingCode` branch merge

**Pull request merged**
